classexec.exe   --action print
classexec.exe 0821  --action print
classexec.exe 0826  --action print
classexec.exe 0830  --action print
classexec.exe 0909.txt  --action print
classexec.exe 0910  --action print
classexec.exe 0916  --action print
classexec.exe 1.coffee  --action print
classexec.exe 4695.coffee  --action print
classexec.exe a.coffee  --action print
classexec.exe aa.coffee  --action print
classexec.exe abc  --action print
classexec.exe abc.coffee  --action print
classexec.exe abcd.csv  --action print
classexec.exe appeared_count.coffee  --action print
classexec.exe batch.coffee  --action print
classexec.exe batch_summarize.coffee  --action print
classexec.exe batches_wo_package.coffee  --action print
classexec.exe beizhu  --action print
classexec.exe bianqianxue.csv  --action print
classexec.exe blood_seq.coffee  --action print
classexec.exe bone.coffee  --action print
classexec.exe bone_data  --action print
classexec.exe bqx.csv  --action print
classexec.exe change_appeared.coffee  --action print
classexec.exe check_products.coffee  --action print
classexec.exe combos_of.coffee  --action print
classexec.exe completion.coffee  --action print
classexec.exe daily_report.coffee  --action print
classexec.exe daily_status.coffee  --action print
classexec.exe delete_item.coffee  --action print
classexec.exe division_count.coffee  --action print
classexec.exe division_name_seq.coffee  --action print
classexec.exe duplicate_item_name.coffee  --action print
classexec.exe dz.csv  --action print
classexec.exe empty_samplings.coffee  --action print
classexec.exe error_package.coffee  --action print
classexec.exe fsk.coffee  --action print
classexec.exe gjqc.coffee  --action print
classexec.exe guests.csv  --action print
classexec.exe helishi.coffee  --action print
classexec.exe hls_correction.coffee  --action print
classexec.exe immunoassay.coffee  --action print
classexec.exe immunoassay_of.coffee  --action print
classexec.exe jg.zip  --action print
classexec.exe kgc.csv  --action print
classexec.exe kgc_code  --action print
classexec.exe liangduiban_results.coffee  --action print
classexec.exe log  --action print
classexec.exe mianyi.csv  --action print
classexec.exe my.csv  --action print
classexec.exe ningxue.csv  --action print
classexec.exe non_empty.coffee  --action print
classexec.exe pck2.coffee  --action print
classexec.exe print.bat  --action print
classexec.exe problematic.coffee  --action print
classexec.exe quanxue.csv  --action print
classexec.exe remove_barcode_image.coffee  --action print
classexec.exe remove_image.coffee  --action print
classexec.exe remove_item.coffee  --action print
classexec.exe remove_sampling.coffee  --action print
classexec.exe remove_samplings_xray.coffee  --action print
classexec.exe remove_those_image.coffee  --action print
classexec.exe remove_value.coffee  --action print
classexec.exe sample_blood.coffee  --action print
classexec.exe search_wk.coffee  --action print
classexec.exe set_department_unfinished.coffee  --action print
classexec.exe shenghua.coffee  --action print
classexec.exe shenghua.csv  --action print
classexec.exe shenghua_mianyi.coffee  --action print
classexec.exe summarize.coffee  --action print
classexec.exe tct  --action print
classexec.exe tct_rename.coffee  --action print
classexec.exe temp  --action print
classexec.exe touch.coffee  --action print
classexec.exe touch_unappeared.coffee  --action print
classexec.exe touch_zkjg.coffee  --action print
classexec.exe unsampled.coffee  --action print
classexec.exe update_division.coffee  --action print
classexec.exe update_doctor_name.coffee  --action print
classexec.exe update_shenghua_doctor.coffee  --action print
classexec.exe update_ytb_value.coffee  --action print
classexec.exe wlzx.coffee  --action print
classexec.exe yigan.csv  --action print
classexec.exe youmen.csv  --action print
classexec.exe zip_reports  --action print
classexec.exe zip_reports_of_company.coffee  --action print
classexec.exe zip_reports_of_company.coffee__  --action print
classexec.exe zip_reports_of_company.sh  --action print
classexec.exe 机关TCT  --action print
classexec.exe 大生知行.zip  --action print
classexec.exe 电子六所.zip  --action print
classexec.exe 和利时（外检）.zip  --action print
classexec.exe 中科院机关（外检）.zip  --action print
classexec.exe 中科院科技服务公司.zip  --action print
