#!/usr/bin/env bash
#./js2coffee
mongo ./import/dropdb_hswk.js
cd samples_data
find . -mindepth 1 -maxdepth 1 -type d | sort | while read dir; do
  dir=${dir:2}
  echo $dir
  echo -e "Importing Collection: $dir...\c"
  if [ "$dir" = "suggestions" ]; then
    ../import/md2json_hswk $dir/*.md
  else
    ../import/coffee2json_hswk $dir/*.coffee
  fi
  echo "Done"
done
cd ..
